### ISSUE TITLE
Move venA-textToFolio-Iliad.csv over to the archive

### ISSUE THREAD

**Issue by brclar15** [homermultitext/hmt-archive#190]
Drop the venA-textToFolio-Iliad.csv file from hc-il18 repo in to the archive, and all future VA editing repos.

This will reflect the existence of line urn:cts:greekLit:tlg0012.tlg001.msA:18.604_605, where the master file incorrectly has 18.604 and then 18.605.

**Comment by neelsmith** [comment]
done
