### ISSUE TITLE
Revise edition of urn:cts:greekLit:tlg5026.msA.hmt:10.1005 and 1006

### ISSUE THREAD

**Issue by neelsmith** [homermultitext/hmt-archive#250]
What's going on with use of dashes?  Check against MS.

**Comment by StephanieML** [comment]
doesn't appear to be anything weird in 1005, but I took the one in 1006 and made it a high stop. Will show up in pull request.

**Comment by StephanieML** [comment]
see pull request

**Comment by neelsmith** [comment]
merged
