### ISSUE TITLE
Composite texts seem to be randomly assembled

### ISSUE THREAD

**Issue by Eumaeus** [homermultitext/hmt-archive#464]

**Comment by Eumaeus** [comment]
To fix… 

1. In `hmt-cexbuilder`, run `sbt testOnly org.homermultitext.hmtcexbuilder.DataCollectorSpec`. Confirm that this test fails.
1. In `hmt-cexbuilder/src/main/scala/DataCollector.scala`, edit line 62 so it is thus:
          fileVector.filter(_.getName.endsWith(extension)).sorted
1. Re-run test. Confirm that it passes.

**Comment by neelsmith** [comment]
fixed
