### ISSUE TITLE
Bad DSE Records, possible missing (unedited) scholia

### ISSUE THREAD

**Issue by Eumaeus** [homermultitext/hmt-archive#488]
The following DSE records claim to match passages that are elsewhere correctly recorded in DSE. These point to scholia on images that do not seem to be in our data.

urn:cite2:hmt:va_dse.v1:schol8137#DSE record for scholion 13.A7#urn:cts:greekLit:tlg5026.msAim.dipl:13.A7#urn:cite2:hmt:vaimg.2017a:VA175VN_0677@0.434,0.4786,0.072,0.0518#urn:cite2:hmt:msA.v1:175v#22040

urn:cite2:hmt:va_dse.v1:schol8136#DSE record for scholion 13.A6#urn:cts:greekLit:tlg5026.msAim.dipl:13.A6#urn:cite2:hmt:vaimg.2017a:VA175VN_0677@0.426,0.3839,0.079,0.0601#urn:cite2:hmt:msA.v1:175v#22039

urn:cite2:hmt:va_dse.v1:schol8138#DSE record for scholion 13.A8#urn:cts:greekLit:tlg5026.msAim.dipl:13.A8#urn:cite2:hmt:vaimg.2017a:VA175VN_0677@0.444,0.6476,0.056,0.0376#urn:cite2:hmt:msA.v1:175v#22041

**Comment by neelsmith** [comment]
DSE now validates for all DSE records in published archive.
