### ISSUE TITLE
Scholion Edition Misspelling Venetus A 17.21

### ISSUE THREAD

**Issue by Acsmith0413** [homermultitext/hmt-archive#490]
There is a mistake in the edits of the scholion on what should be line 17.21 that reads:
οὔτε συος κάπρου κατ επίτασιν ἀλκι τερος γὰρ ὁ κάπρος· δι ὃ ἐπὶ πᾶσι τέτακται οὐ κ’ἄλλα διὰ τὸ θυμικώτερον εἶναι τὸν κάπρον τῶν ἄλλων ζώων ἐπενήνοχε προς αὔξησιν καὶ ἔστιν σῦς μὲν τὸ γενικὸν , κάπρος δὲ τὸ εἰδικον , ἀπο τοῦ κάπτειν ⁑

However, ἀλκι τερος should be ἀλκιμωτερος according to the manuscript.

**Comment by neelsmith** [comment]
This is actually legitimate:  the facsimile is displaying a pure diplomatic version without expansion of abbreviations or added materials.
