### ISSUE TITLE
#!catalog for scholia is not idea in CEX release output

### ISSUE THREAD

**Issue by Eumaeus** [homermultitext/hmt-archive#507]
In `/archive/scholia-xml-composites` we have a nice file with catalog info for the scholia texts. That data is not used by the `release2020.sc` script, which is a shame, since it is better (more descriptive of the different texts) than the one that gets put in the final CEX.

This is not a hard fix. I'll write a fix and test it in a branch.

**Comment by neelsmith** [comment]
Superseded by current build system.
