### ISSUE TITLE
Bad sequence of pages in VA codex model?

### ISSUE THREAD

**Issue by neelsmith** [homermultitext/hmt-archive#508]
I was looking in the images of Venetus A for a scholion that Erbse places at 23.866, but encountered an odd thing (http://www.homermultitext.org/facsimiles/venetus-a-2020/pages/urn_cite2_hmt_msA-v1_310v.html). The images skip from 305v to 310v (I've attached a screen shot, so you can see what I saw). Obviously it is not the most pressing matter at the moment, but it seemed worth passing along since it came up.

**Comment by neelsmith** [comment]
Provisionally assigning to Eumaeus in hopes that if he finds the bad datum we can make a new HMT release and he can start running the massive build for a new fascimile?

**Comment by Eumaeus** [comment]
On it! Or… will be on it when I can come up for air! Should be an easy fix.

**Comment by neelsmith** [comment]
Is this currently fixed?  IF so @Eumaeus can you close this issue?

**Comment by neelsmith** [comment]
fixed. closing
